displayName=Alert Bad Offers
author=itssapir
description=Alerts and requires additional confirmation when setting GE offers with large deviations from the market price
tags=Grand Exchange, Flipping, GE, Alert, Price
version=1.0.1
plugins=com.alertBadOffers.AlertBadOffersPlugin
build=standard